### ISSUE TITLE
"Check structure now" reports issues

### ISSUE THREAD

**Issue by rlaemmel** [cEhlen/OCL101Companies#1]
cc @cEhlen 

<pre>
checking structure...
Multiplicity constraint violation in association `DepartmentOf':
  Object `Dev11Dep' of class `Department' is connected to 0 objects of class `Company'
  at association end `company' but the multiplicity is specified as `1'.
Multiplicity constraint violation in association `DepartmentOf':
  Object `Dev1Dep' of class `Department' is connected to 0 objects of class `Company'
  at association end `company' but the multiplicity is specified as `1'.
checked structure in 4ms.
checking structure, found errors.
</pre>

**Comment by cEhlen** [comment]
I forgot to add the option to have no 'company'. This is now fixed by setting the Company to 0..1. Now OCL will take care of 'Every department needs to be connected to a company'.
