### ISSUE TITLE
Shouldn't this be compositions?

### ISSUE THREAD

**Issue by rlaemmel** [cEhlen/OCL101Companies#2]
cc @cEhlen 

<pre>
-- Associations

association WorksIn between
    Employee[*] role employees
    Department[1] role department
end

association SubdepartmentOf between
    Department[*] role subdepartments
    Department[0..1] role parent
end

association DepartmentOf between
    Department[*] role departments
    Company[1] role company
end
</pre>

**Comment by cEhlen** [comment]
I agree, this should be a composition.
